/* EXAMPLE */
export const GET_EXAMPLES = 'GET_EXAMPLES';
export const GET_EXAMPLES_SUCCESS = 'GET_EXAMPLES_SUCCESS';
export const GET_EXAMPLES_FAIL = 'GET_EXAMPLES_FAIL';

export const GET_EXAMPLE_DETAIL = 'GET_EXAMPLE_DETAIL';
export const GET_EXAMPLE_DETAIL_SUCCESS = 'GET_EXAMPLES_DETAIL_SUCCESS';
export const GET_EXAMPLE_DETAIL_FAIL = 'GET_EXAMPLES_DETAIL_FAIL';

export const GET_NLUDATA_INFO = 'GET_NLUDATA_INFO';
export const GET_NLUDATA_INFO_SUCCESS = 'GET_NLUDATA_INFO_SUCCESS';
export const GET_NLUDATA_INFO_FAIL = 'GET_NLUDATA_INFO_FAIL';
